### ISSUE TITLE
add temp and pressure to this?

### ISSUE THREAD

**Issue by jaredduggan** [SANdood/homebridge-purpleair#3]
Good afternoon! Just wondering if you you are able to add the ability to pull the temperature, humidity, and pressure to this also?

**Comment by SANdood** [comment]
The temperature and humidity readings are not meaningful - they exist only because they are required for the sensor software to calibrate the readings (temp & humidity directly affect the sensors). And the pressure sensor isn't calibrated, so useful only for relative comparisons.

That said, feel free to extend the code to return these values...I myself have no use for them.

**Comment by jaredduggan** [comment]
Thanks, Barry. I was not sure that is how the sensors work. I appreciate your response.

Jared Duggan

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
